{
    _events: [Object: null prototype] { },
    _eventsCount: 0,
        _maxListeners: undefined,
            banchojs: BanchoClient {
        _events: [Object: null prototype] {
            error: [Function(anonymous)],
                PM: [Function(anonymous)],
                    CM: [Function(anonymous)],
                        connected: [Function(anonymous)]
        },
        _eventsCount: 4,
            _maxListeners: 50,
                username: 'Kuda_Terbang',
                    password: '006a9c15',
                        host: 'irc.ppy.sh',
                            port: 6667,
                                rateLimiter: RateLimiterQueue {
            _queueLimiters: [Object],
                _limiterFlexible: [RateLimiterMemory],
                    _maxQueueSize: 4294967295
        },
        client: Socket {
            connecting: false,
                _hadError: false,
                    _parent: null,
                        _host: 'irc.ppy.sh',
                            _readableState: [ReadableState],
                                _events: [Object: null prototype],
                                    _eventsCount: 5,
                                        _maxListeners: undefined,
                                            _writableState: [WritableState],
                                                allowHalfOpen: false,
                                                    _sockname: null,
                                                        _pendingData: null,
                                                            _pendingEncoding: '',
                                                                server: null,
                                                                    _server: null,
                                                                        timeout: 60000,
                                                                            [Symbol(async_id_symbol)]: 8,
                                                                                [Symbol(kHandle)]: [TCP],
                                                                                    [Symbol(lastWriteQueueSize)]: 0,
                                                                                        [Symbol(timeout)]: Timeout {
                _idleTimeout: 60000,
                    _idlePrev: [TimersList],
                        _idleNext: [TimersList],
                            _idleStart: 14495,
                                _onTimeout: [Function: bound],
                                    _timerArgs: undefined,
                                        _repeat: null,
                                            _destroyed: false,
                                                [Symbol(refed)]: false,
                                                    [Symbol(kHasPrimitive)]: false,
                                                        [Symbol(asyncId)]: 6,
                                                            [Symbol(triggerId)]: 1
            },
            [Symbol(kBuffer)]: null,
                [Symbol(kBufferCb)]: null,
                    [Symbol(kBufferGen)]: null,
                        [Symbol(kCapture)]: false,
                            [Symbol(kSetNoDelay)]: false,
                                [Symbol(kSetKeepAlive)]: false,
                                    [Symbol(kSetKeepAliveInitialDelay)]: 0,
                                        [Symbol(kBytesRead)]: 0,
                                            [Symbol(kBytesWritten)]: 0
        },
        connectState: Symbol(Connected),
            reconnect: true,
                reconnectTimeout: null,
                    connectCallback: null,
                        joinCallbacks: [],
                            partCallbacks: [],
                                users: WeakValueMap {
            map: [Map],
                finalizationRegistry: FinalizationRegistry { }
        },
        usersById: WeakValueMap {
            map: Map(0) { },
            finalizationRegistry: FinalizationRegistry { }
        },
        channels: { '#osu': [BanchoChannel], '#indonesian': [BanchoChannel] },
        messagesQueue: [],
            ignoreClose: false,
                [Symbol(kCapture)]: false
    },
    ircUsername: 'Redakla',
        whoisUserCallback: null,
            whoisChannelsCallback: null,
                whoisEndCallback: null,
                    whoisUserNotFoundCallback: null,
                        whoisPromise: null,
                            wherePromise: null,
                                statsPromise: null,
                                    listenersInitialized: false,
                                        [Symbol(kCapture)]: false
}